# Generated by Django 5.0.7 on 2024-08-01 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tg_user_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('language_code', models.CharField(blank=True, max_length=10)),
                ('is_premium', models.BooleanField(default=False)),
                ('allows_write_to_pm', models.BooleanField(default=False)),
                ('wallet_address', models.CharField(blank=True, max_length=66)),
                ('app_name', models.CharField(blank=True, max_length=100)),
                ('registred_at', models.DateTimeField(auto_now_add=True)),
                ('who_invited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
