# Generated by Django 5.0.7 on 2024-08-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_hash',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
