# Generated by Django 5.0.7 on 2024-08-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_auth_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goy_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ton_balance',
            field=models.FloatField(default=0),
        ),
    ]
