# Generated by Django 5.0.7 on 2024-08-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_goy_balance_user_ton_balance'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tg_user_id'], name='core_user_tg_user_908c97_idx'),
        ),
    ]
