# Generated by Django 5.0.7 on 2024-08-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_core_user_tg_user_908c97_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
